version: '3.9'

services:
  postgres:
    container_name: postgres-course-nestjs-container
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'course_nestjs_db'
    networks:
      - postgres
    volumes:
          - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  postgres:
    driver: bridge

volumes:
  postgres: